# Generated by Django 4.2.2 on 2023-06-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boxesRestante1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(max_length=5)),
                ('ocupado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='boxesRestante2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(max_length=5)),
                ('ocupado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='boxesRestante3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(max_length=5)),
                ('ocupado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField()),
                ('celular', models.TextField()),
                ('whatsapp', models.TextField(blank=True, null=True)),
                ('cip', models.TextField()),
                ('pin', models.TextField(blank=True, null=True)),
                ('monto', models.TextField()),
                ('confirmado2', models.DateTimeField(blank=True, null=True)),
                ('smsTicketsPagados', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, max_length=40, null=True)),
                ('correo', models.TextField(blank=True, max_length=20, null=True)),
                ('dni', models.TextField(blank=True, null=True)),
                ('pregunta1', models.TextField(blank=True, max_length=50, null=True)),
                ('pregunta2', models.TextField(blank=True, max_length=50, null=True)),
                ('pregunta3', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField()),
                ('pregunta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='smsValidacionCelular',
            fields=[
                ('correlativo', models.AutoField(primary_key=True, serialize=False)),
                ('celular', models.CharField(max_length=9)),
                ('codigoValidacion', models.CharField(max_length=6)),
                ('fechaSolicitud', models.DateTimeField(blank=True, null=True)),
                ('fechaEnvio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'SMSCelularesyCodigosValidacion',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField()),
                ('codigoseguridad', models.TextField()),
                ('pin', models.TextField(blank=True, null=True)),
                ('pinIntentos', models.PositiveIntegerField(default=0)),
                ('fechaHoraIntentoFallido', models.DateTimeField(blank=True, null=True)),
                ('fechaHoraCambio', models.DateTimeField(blank=True, null=True)),
                ('celular', models.TextField()),
                ('whatsapp', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField()),
                ('numeroBox', models.TextField(default='0', max_length=5)),
                ('cip', models.TextField()),
                ('confirmado2', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, max_length=40, null=True)),
                ('correo', models.TextField(blank=True, max_length=50, null=True)),
                ('dni', models.TextField(blank=True, null=True)),
                ('pregunta1', models.TextField(blank=True, max_length=50, null=True)),
                ('pregunta2', models.TextField(blank=True, max_length=50, null=True)),
                ('intentosIngresoFallido', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fechaHoraIngresoExitoso', models.DateTimeField(blank=True, null=True)),
                ('intentosIngresoOK', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveBigIntegerField(default=100)),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
    ]
