# Generated by Django 4.2.2 on 2023-06-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='codigosCelularValidacion',
            fields=[
                ('correlativo', models.AutoField(primary_key=True, serialize=False)),
                ('celular', models.CharField(max_length=9)),
                ('codigovalidacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CelularesyCodigosValidacion',
            },
        ),
    ]
