# Generated by Django 4.2.1 on 2023-06-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_codigoscelularvalidacion_tipos_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipos',
            old_name='precio',
            new_name='monto',
        ),
    ]
