# Generated by Django 4.2.2 on 2023-06-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_rename_precio_tipos_monto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipos',
            old_name='monto',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='codigoscelularvalidacion',
            name='codigovalidacion',
            field=models.CharField(max_length=6),
        ),
    ]
