# Generated by Django 4.2.2 on 2023-06-08 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_rename_monto_tipos_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='smsValidacionCelular',
            fields=[
                ('correlativo', models.AutoField(primary_key=True, serialize=False)),
                ('celular', models.CharField(max_length=9)),
                ('codigoValidacion', models.CharField(max_length=6)),
                ('fechaHoraEnvio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'SMSCelularesyCodigosValidacion',
            },
        ),
        migrations.DeleteModel(
            name='codigosCelularValidacion',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='recibo',
            new_name='codigoseguridad',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='fechaHora',
            new_name='fechaHoraCambio',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='recibo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='sms',
        ),
        migrations.AddField(
            model_name='pago',
            name='smsTicketsPagados',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='fechaHoraIngresoExitoso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='fechaHoraIntentoFallido',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 15, 59, 29, 360866, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='intentosIngresoFallido',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='intentosIngresoOK',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='pin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cip',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='confirmado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='correo',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='confirmado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
