# Generated by Django 4.2.2 on 2023-06-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_smsvalidacioncelular_delete_codigoscelularvalidacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pago',
            new_name='Pagos',
        ),
    ]
