# Generated by Django 4.2.2 on 2023-06-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0007_rename_pago_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='celular',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='dni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='monto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='pin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smsvalidacioncelular',
            name='estado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='celular',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='cip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='codigoseguridad',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='dni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='fechaHoraCambio',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='fechaHoraIntentoFallido',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='pin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='pinIntentos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tipo',
            field=models.TextField(),
        ),
    ]
