# Generated by Django 4.2.2 on 2023-06-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0008_alter_pagos_celular_alter_pagos_cip_alter_pagos_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='whatsapp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='fechaHoraCambio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='fechaHoraIntentoFallido',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
