# Generated by Django 4.2.2 on 2023-06-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0009_tickets_whatsapp_alter_tickets_fechahoracambio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='confirmado',
        ),
    ]
