# Generated by Django 4.2.2 on 2023-06-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0010_remove_pagos_confirmado_remove_tickets_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='confirmado2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='confirmado2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
